import {
    DEFAULT_OLLAMA_GENERATE_URL,
    DEFAULT_OLLAMA_MODEL,
    SYSTEM_PROMPT,
} from "../../shared/ollama/index";

export const OLLAMA_URL = DEFAULT_OLLAMA_GENERATE_URL;

export const DEFAULT_MODEL = DEFAULT_OLLAMA_MODEL;
export { SYSTEM_PROMPT };
